# The Ultimate List of Medical Specialties and Subspecialties
# https://www.sgu.edu/blog/medical/ultimate-list-of-medical-specialties/
def is_valid_specialty(specialty):
    doctor_specialties = [
    'Allergy and Immunology',
    'Anesthesiology',
        'Critical care medicine',
        'Hospice and palliative care',
        'Pain medicine',
        'Pediatric anesthesiology',
        'Sleep medicine',
    'Dermatology',
        'Dermatopathology',
        'Pediatric dermatology',
        'Procedural dermatology',
    'Diagnostic radiology',
        'Abdominal radiology',
        'Breast imaging',
        'Cardiothoracic radiology',
        'Cardiovascular radiology',
        'Chest radiology',
        'Emergency radiology',
        'Endovascular surgical neuroradiology',
        'Gastrointestinal radiology',
        'Genitourinary radiology',
        'Head and neck radiology',
        'Interventional radiology',
        'Musculoskeletal radiology',
        'Neuroradiology',
        'Nuclear radiology',
        'Pediatric radiology',
        'Radiation oncology',
        'Vascular and interventional radiology',
    'Emergency medicine',
        'Anesthesiology critical care medicine',
        'Emergency medical services',
        'Hospice and palliative medicine',
        'Internal medicine / Critical care medicine',
        'Medical toxicology',
        'Pain medicine',
        'Pediatric emergency medicine',
        'Sports medicine',
        'Undersea and hyperbaric medicine',
    'Family medicine',
        'Adolescent medicine',
        'Geriatric medicine',
        'Hospice and palliative medicine',
        'Pain medicine',
        'Sleep medicine',
        'Sports medicine',
    'Internal medicine',
        'Advanced heart failure and transplant cardiology',
        'Cardiovascular disease',
        'Clinical cardiac electrophysiology',
        'Critical care medicine',
        'Endocrinology, diabetes, and metabolism',
        'Gastroenterology',
        'Geriatric medicine',
        'Hematology',
        'Hematology and oncology',
        'Infectious disease',
        'Internal medicine',
        'Interventional cardiology',
        'Nephrology',
        'Oncology',
        'Pediatric internal medicine',
        'Pulmonary disease',
        'Pulmonary disease and critical care medicine',
        'Rheumatology',
        'Sleep medicine',
        'Sports medicine',
        'Transplant hepatology',
    'Medical genetics',
        'Biochemical genetics',
        'Clinical cytogenetics',
        'Clinical genetics',
        'Molecular genetic pathology',
    'Neurology',
        'Brain injury medicine',
        'Child neurology',
        'Clinical neurophysiology',
        'Endovascular surgical neuroradiology',
        'Hospice and palliative medicine',
        'Neurodevelopmental disabilities',
        'Neuromuscular medicine',
        'Pain medicine',
        'Sleep medicine',
        'Vascular neurology',
    'Nuclear medicine',
    'Obstetrics and gynecology',
        'Female pelvic medicine and reconstructive surgery',
        'Gynecologic oncology',
        'Maternal-fetal medicine',
        'Reproductive endocrinologists and infertility',
    'Ophthalmology',
        'Anterior segment/cornea ophthalmology',
        'Glaucoma ophthalmology',
        'Neuro-ophthalmology',
        'Ocular oncology',
        'Oculoplastics/orbit',
        'Ophthalmic Plastic & Reconstructive Surgery',
        'Retina/uveitis',
        'Strabismus/pediatric ophthalmology',
    'Pathology',
        'Anatomical pathology',
        'Blood banking and transfusion medicine',
        'Chemical pathology',
        'Clinical pathology',
        'Cytopathology',
        'Forensic pathology',
        'Genetic pathology',
        'Hematology',
        'Immunopathology',
        'Medical microbiology',
        'Molecular pathology',
        'Neuropathology',
        'Pediatric pathology',
    'Pediatrics',
        'Adolescent medicine',
        'Child abuse pediatrics',
        'Developmental-behavioral pediatrics',
        'Neonatal-perinatal medicine',
        'Pediatric cardiology',
        'Pediatric critical care medicine',
        'Pediatric endocrinology',
        'Pediatric gastroenterology',
        'Pediatric hematology-oncology',
        'Pediatric infectious diseases',
        'Pediatric nephrology',
        'Pediatric pulmonology',
        'Pediatric rheumatology',
        'Pediatric sports medicine',
        'Pediatric transplant hepatology',
    'Physical medicine and Rehabilitation',
        'Brain injury medicine',
        'Hospice and palliative medicine',
        'Neuromuscular medicine',
        'Pain medicine',
        'Pediatric rehabilitation medicine',
        'Spinal cord injury medicine',
        'Sports medicine',
    'Preventive medicine',
        'Aerospace medicine',
        'Medical toxicology',
        'Occupational medicine',
        'Public health medicine',
    'Psychiatry',
        'Addiction psychiatry',
        'Administrative psychiatry',
        'Child and adolescent psychiatry',
        'Community psychiatry',
        'Consultation/liaison psychiatry',
        'Emergency psychiatry',
        'Forensic psychiatry',
        'Geriatric psychiatry',
        'Mental retardation psychiatry',
        'Military psychiatry',
        'Pain medicine',
        'Psychiatric research',
        'Psychosomatic medicine',
    'Radiation oncology',
        'Hospice and palliative medicine',
        'Pain medicine',
    'Surgery',
        'Colon and rectal surgery',
        'General surgery',
        'Surgical critical care',
        'Gynecologic oncology',
        'Plastic surgery',
        'Craniofacial surgery',
        'Hand surgery',
        'Neurological surgery',
        'Endovascular surgical neuroradiology',
        'Ophthalmic surgery',
        'Oral and maxillofacial surgery',
        'Orthopaedic surgery',
        'Adult reconstructive orthopaedics',
        'Foot and ankle orthopaedics',
        'Musculoskeletal oncology',
        'Orthopaedic sports medicine',
        'Orthopaedic surgery of the spine',
        'Orthopaedic trauma',
        'Pediatric orthopaedics',
        'Otolaryngology',
        'Pediatric otolaryngology',
        'Otology neurotology',
        'Pediatric surgery',
        'Neonatal',
        'Prenatal',
        'Trauma',
        'Pediatric oncology',
        'Surgical Intensivists, specializing in critical care patients',
        'Thoracic Surgery',
        'Congenital cardiac surgery',
        'Thoracic surgery-integrated',
        'Vascular surgery',
    'Urology',
        'Pediatric urology',
        'Urologic oncology',
        'Renal transplant',
        'Male infertility',
        'Calculi',
        'Female urology',
        'Neurourology',
    ]

    doctor_specialties = [specialty.upper() for specialty in doctor_specialties]
    return specialty.upper() in doctor_specialties

city_dict = {
    'Baliuag': 'Baliwag',
    'Libjo (Albor)': 'Libjo',
    'Cordoba': 'Cordova',
    'Science of Muñoz': 'Muñoz',
    'Pozzorubio': 'Pozorrubio',
    'Baloi': 'Balo-i'
}

def is_valid_city(city):
    cities_in_ph = [
        'Bangued',
        'Boliney',
        'Bucay',
        'Bucloc',
        'Daguioman',
        'Danglas',
        'Dolores',
        'La Paz',
        'Lacub',
        'Lagangilang',
        'Lagayan',
        'Langiden',
        'Licuan-Baay',
        'Luba',
        'Malibcong',
        'Manabo',
        'Peñarrubia',
        'Pidigan',
        'Pilar',
        'Sallapadan',
        'San Isidro',
        'San Juan',
        'San Quintin',
        'Tayum',
        'Tineg',
        'Tubo',
        'Villaviciosa',
        'Buenavista',
        'Butuan',
        'Cabadbaran',
        'Carmen',
        'Jabonga',
        'Kitcharao',
        'Las Nieves',
        'Magallanes',
        'Nasipit',
        'Remedios T. Romualdez',
        'Santiago',
        'Tubay',
        'Bayugan',
        'Bunawan',
        'Esperanza',
        'La Paz',
        'Loreto',
        'Prosperidad',
        'Rosario',
        'San Francisco',
        'San Luis',
        'Santa Josefa',
        'Sibagat',
        'Talacogon',
        'Trento',
        'Veruela',
        'Altavas',
        'Balete',
        'Banga',
        'Batan',
        'Buruanga',
        'Ibajay',
        'Kalibo',
        'Lezo',
        'Libacao',
        'Madalag',
        'Makato',
        'Malay',
        'Malinao',
        'Nabas',
        'New Washington',
        'Numancia',
        'Tangalan',
        'Bacacay',
        'Camalig',
        'Daraga',
        'Guinobatan',
        'Jovellar',
        'Legazpi',
        'Libon',
        'Ligao',
        'Malilipot',
        'Malinao',
        'Manito',
        'Oas',
        'Pio Duran',
        'Polangui',
        'Rapu-Rapu',
        'Santo Domingo',
        'Tabaco',
        'Tiwi',
        'Anini-y',
        'Barbaza',
        'Belison',
        'Bugasong',
        'Caluya',
        'Culasi',
        'Hamtic',
        'Laua-an',
        'Libertad',
        'Pandan',
        'Patnongon',
        'San Jose de Buenavista',
        'San Remigio',
        'Sebaste',
        'Sibalom',
        'Tibiao',
        'Tobias Fornier',
        'Valderrama',
        'Calanasan',
        'Conner',
        'Flora',
        'Kabugao',
        'Luna',
        'Pudtol',
        'Santa Marcela',
        'Baler',
        'Casiguran',
        'Dilasag',
        'Dinalungan',
        'Dingalan',
        'Dipaculao',
        'Maria Aurora',
        'San Luis',
        'Akbar',
        'Al-Barka',
        'Hadji Mohammad Ajul',
        'Hadji Muhtamad',
        'Isabela',
        'Lamitan',
        'Lantawan',
        'Maluso',
        'Sumisip',
        'Tabuan-Lasa',
        'Tipo-Tipo',
        'Tuburan',
        'Ungkaya Pukan',
        'Abucay',
        'Bagac',
        'Balanga',
        'Dinalupihan',
        'Hermosa',
        'Limay',
        'Mariveles',
        'Morong',
        'Orani',
        'Orion',
        'Pilar',
        'Samal',
        'Basco',
        'Itbayat',
        'Ivana',
        'Mahatao',
        'Sabtang',
        'Uyugan',
        'Agoncillo',
        'Alitagtag',
        'Balayan',
        'Balete',
        'Batangas',
        'Bauan',
        'Calaca',
        'Calatagan',
        'Cuenca',
        'Ibaan',
        'Laurel',
        'Lemery',
        'Lian',
        'Lipa',
        'Lobo',
        'Mabini',
        'Malvar',
        'Mataasnakahoy',
        'Nasugbu',
        'Padre Garcia',
        'Rosario',
        'San Jose',
        'San Juan',
        'San Luis',
        'San Nicolas',
        'San Pascual',
        'Santa Teresita',
        'Santo Tomas',
        'Taal',
        'Talisay',
        'Tanauan',
        'Taysan',
        'Tingloy',
        'Tuy',
        'Atok',
        'Baguio',
        'Bakun',
        'Bokod',
        'Buguias',
        'Itogon',
        'Kabayan',
        'Kapangan',
        'Kibungan',
        'La Trinidad',
        'Mankayan',
        'Sablan',
        'Tuba',
        'Tublay',
        'Almeria',
        'Biliran',
        'Cabucgayan',
        'Caibiran',
        'Culaba',
        'Kawayan',
        'Maripipi',
        'Naval',
        'Alburquerque',
        'Alicia',
        'Anda',
        'Antequera',
        'Baclayon',
        'Balilihan',
        'Batuan',
        'Bien Unido',
        'Bilar',
        'Buenavista',
        'Calape',
        'Candijay',
        'Carmen',
        'Catigbian',
        'Clarin',
        'Corella',
        'Cortes',
        'Dagohoy',
        'Danao',
        'Dauis',
        'Dimiao',
        'Duero',
        'Garcia Hernandez',
        'Getafe',
        'Guindulman',
        'Inabanga',
        'Jagna',
        'Lila',
        'Loay',
        'Loboc',
        'Loon',
        'Mabini',
        'Maribojoc',
        'Panglao',
        'Pilar',
        'President Carlos P. Garcia',
        'Sagbayan',
        'San Isidro',
        'San Miguel',
        'Sevilla',
        'Sierra Bullones',
        'Sikatuna',
        'Tagbilaran',
        'Talibon',
        'Trinidad',
        'Tubigon',
        'Ubay',
        'Valencia',
        'Baungon',
        'Cabanglasan',
        'Damulog',
        'Dangcagan',
        'Don Carlos',
        'Impasugong',
        'Kadingilan',
        'Kalilangan',
        'Kibawe',
        'Kitaotao',
        'Lantapan',
        'Libona',
        'Malaybalay',
        'Malitbog',
        'Manolo Fortich',
        'Maramag',
        'Pangantucan',
        'Quezon',
        'San Fernando',
        'Sumilao',
        'Talakag',
        'Valencia',
        'Angat',
        'Balagtas',
        'Baliwag',
        'Bocaue',
        'Bulakan',
        'Bustos',
        'Calumpit',
        'Doña Remedios Trinidad',
        'Guiguinto',
        'Hagonoy',
        'Malolos',
        'Marilao',
        'Meycauayan',
        'Norzagaray',
        'Obando',
        'Pandi',
        'Paombong',
        'Plaridel',
        'Pulilan',
        'San Ildefonso',
        'San Jose del Monte',
        'San Miguel',
        'San Rafael',
        'Santa Maria',
        'Abulug',
        'Alcala',
        'Allacapan',
        'Amulung',
        'Aparri',
        'Baggao',
        'Ballesteros',
        'Buguey',
        'Calayan',
        'Camalaniugan',
        'Claveria',
        'Enrile',
        'Gattaran',
        'Gonzaga',
        'Iguig',
        'Lal-lo',
        'Lasam',
        'Pamplona',
        'Peñablanca',
        'Piat',
        'Rizal',
        'Sanchez-Mira',
        'Santa Ana',
        'Santa Praxedes',
        'Santa Teresita',
        'Santo Niño',
        'Solana',
        'Tuao',
        'Tuguegarao',
        'Basud',
        'Capalonga',
        'Daet',
        'Jose Panganiban',
        'Labo',
        'Mercedes',
        'Paracale',
        'San Lorenzo Ruiz',
        'San Vicente',
        'Santa Elena',
        'Talisay',
        'Vinzons',
        'Baao',
        'Balatan',
        'Bato',
        'Bombon',
        'Buhi',
        'Bula',
        'Cabusao',
        'Calabanga',
        'Camaligan',
        'Canaman',
        'Caramoan',
        'Del Gallego',
        'Gainza',
        'Garchitorena',
        'Goa',
        'Iriga',
        'Lagonoy',
        'Libmanan',
        'Lupi',
        'Magarao',
        'Milaor',
        'Minalabac',
        'Nabua',
        'Naga',
        'Ocampo',
        'Pamplona',
        'Pasacao',
        'Pili',
        'Presentacion',
        'Ragay',
        'Sagñay',
        'San Fernando',
        'San Jose',
        'Sipocot',
        'Siruma',
        'Tigaon',
        'Tinambac',
        'Catarman',
        'Guinsiliban',
        'Mahinog',
        'Mambajao',
        'Sagay',
        'Cuartero',
        'Dao',
        'Dumalag',
        'Dumarao',
        'Ivisan',
        'Jamindan',
        'Ma-ayon',
        'Mambusao',
        'Panay',
        'Panitan',
        'Pilar',
        'Pontevedra',
        'President Roxas',
        'Roxas',
        'Sapian',
        'Sigma',
        'Tapaz',
        'Bagamanoc',
        'Baras',
        'Bato',
        'Caramoran',
        'Gigmoto',
        'Pandan',
        'Panganiban',
        'San Andres',
        'San Miguel',
        'Viga',
        'Virac',
        'Alfonso',
        'Amadeo',
        'Bacoor',
        'Carmona',
        'Cavite',
        'Dasmariñas',
        'General Emilio Aguinaldo',
        'General Mariano Alvarez',
        'General Trias',
        'Imus',
        'Indang',
        'Kawit',
        'Magallanes',
        'Maragondon',
        'Mendez',
        'Naic',
        'Noveleta',
        'Rosario',
        'Silang',
        'Tagaytay',
        'Tanza',
        'Ternate',
        'Trece Martires',
        'Alcantara',
        'Alcoy',
        'Alegria',
        'Aloguinsan',
        'Argao',
        'Asturias',
        'Badian',
        'Balamban',
        'Bantayan',
        'Barili',
        'Bogo',
        'Boljoon',
        'Borbon',
        'Carcar',
        'Carmen',
        'Catmon',
        'Cebu',
        'Compostela',
        'Consolacion',
        'Cordova',
        'Daanbantayan',
        'Dalaguete',
        'Danao',
        'Dumanjug',
        'Ginatilan',
        'Lapu-Lapu',
        'Liloan',
        'Madridejos',
        'Malabuyoc',
        'Mandaue',
        'Medellin',
        'Minglanilla',
        'Moalboal',
        'Naga',
        'Oslob',
        'Pilar',
        'Pinamungajan',
        'Poro',
        'Ronda',
        'Samboan',
        'San Fernando',
        'San Francisco',
        'San Remigio',
        'Santa Fe',
        'Santander',
        'Sibonga',
        'Sogod',
        'Tabogon',
        'Tabuelan',
        'Talisay',
        'Toledo',
        'Tuburan',
        'Tudela',
        'Alamada',
        'Aleosan',
        'Antipas',
        'Arakan',
        'Banisilan',
        'Carmen',
        'Kabacan',
        'Kidapawan',
        'Libungan',
        'M\'lang',
        'Magpet',
        'Makilala',
        'Matalam',
        'Midsayap',
        'Pigcawayan',
        'Pikit',
        'President Roxas',
        'Tulunan',
        'Compostela',
        'Laak',
        'Mabini',
        'Maco',
        'Maragusan',
        'Mawab',
        'Monkayo',
        'Montevista',
        'Nabunturan',
        'New Bataan',
        'Pantukan',
        'Asuncion',
        'Braulio E. Dujali',
        'Carmen',
        'Kapalong',
        'New Corella',
        'Panabo',
        'Samal',
        'San Isidro',
        'Santo Tomas',
        'Tagum',
        'Talaingod',
        'Bansalan',
        'Davao',
        'Digos',
        'Hagonoy',
        'Kiblawan',
        'Magsaysay',
        'Malalag',
        'Matanao',
        'Padada',
        'Santa Cruz',
        'Sulop',
        'Don Marcelino',
        'Jose Abad Santos',
        'Malita',
        'Santa Maria',
        'Sarangani',
        'Baganga',
        'Banaybanay',
        'Boston',
        'Caraga',
        'Cateel',
        'Governor Generoso',
        'Lupon',
        'Manay',
        'Mati',
        'San Isidro',
        'Tarragona',
        'Basilisa',
        'Cagdianao',
        'Dinagat',
        'Libjo',
        'Loreto',
        'San Jose',
        'Tubajon',
        'Arteche',
        'Balangiga',
        'Balangkayan',
        'Borongan',
        'Can-avid',
        'Dolores',
        'General MacArthur',
        'Giporlos',
        'Guiuan',
        'Hernani',
        'Jipapad',
        'Lawaan',
        'Llorente',
        'Maslog',
        'Maydolong',
        'Mercedes',
        'Oras',
        'Quinapondan',
        'Salcedo',
        'San Julian',
        'San Policarpo',
        'Sulat',
        'Taft',
        'Buenavista',
        'Jordan',
        'Nueva Valencia',
        'San Lorenzo',
        'Sibunag',
        'Aguinaldo',
        'Alfonso Lista',
        'Asipulo',
        'Banaue',
        'Hingyon',
        'Hungduan',
        'Kiangan',
        'Lagawe',
        'Lamut',
        'Mayoyao',
        'Tinoc',
        'Adams',
        'Bacarra',
        'Badoc',
        'Bangui',
        'Banna',
        'Batac',
        'Burgos',
        'Carasi',
        'Currimao',
        'Dingras',
        'Dumalneg',
        'Laoag',
        'Marcos',
        'Nueva Era',
        'Pagudpud',
        'Paoay',
        'Pasuquin',
        'Piddig',
        'Pinili',
        'San Nicolas',
        'Sarrat',
        'Solsona',
        'Vintar',
        'Alilem',
        'Banayoyo',
        'Bantay',
        'Burgos',
        'Cabugao',
        'Candon',
        'Caoayan',
        'Cervantes',
        'Galimuyod',
        'Gregorio del Pilar',
        'Lidlidda',
        'Magsingal',
        'Nagbukel',
        'Narvacan',
        'Quirino',
        'Salcedo',
        'San Emilio',
        'San Esteban',
        'San Ildefonso',
        'San Juan',
        'San Vicente',
        'Santa Catalina',
        'Santa Cruz',
        'Santa Lucia',
        'Santa Maria',
        'Santa',
        'Santiago',
        'Santo Domingo',
        'Sigay',
        'Sinait',
        'Sugpon',
        'Suyo',
        'Tagudin',
        'Vigan',
        'Ajuy',
        'Alimodian',
        'Anilao',
        'Badiangan',
        'Balasan',
        'Banate',
        'Barotac Nuevo',
        'Barotac Viejo',
        'Batad',
        'Bingawan',
        'Cabatuan',
        'Calinog',
        'Carles',
        'Concepcion',
        'Dingle',
        'Dueñas',
        'Dumangas',
        'Estancia',
        'Guimbal',
        'Igbaras',
        'Iloilo',
        'Janiuay',
        'Lambunao',
        'Leganes',
        'Lemery',
        'Leon',
        'Maasin',
        'Miagao',
        'Mina',
        'New Lucena',
        'Oton',
        'Passi',
        'Pavia',
        'Pototan',
        'San Dionisio',
        'San Enrique',
        'San Joaquin',
        'San Miguel',
        'San Rafael',
        'Santa Barbara',
        'Sara',
        'Tigbauan',
        'Tubungan',
        'Zarraga',
        'Alicia',
        'Angadanan',
        'Aurora',
        'Benito Soliven',
        'Burgos',
        'Cabagan',
        'Cabatuan',
        'Cauayan',
        'Cordon',
        'Delfin Albano',
        'Dinapigue',
        'Divilacan',
        'Echague',
        'Gamu',
        'Ilagan',
        'Jones',
        'Luna',
        'Maconacon',
        'Mallig',
        'Naguilian',
        'Palanan',
        'Quezon',
        'Quirino',
        'Ramon',
        'Reina Mercedes',
        'Roxas',
        'San Agustin',
        'San Guillermo',
        'San Isidro',
        'San Manuel',
        'San Mariano',
        'San Mateo',
        'San Pablo',
        'Santa Maria',
        'Santiago',
        'Santo Tomas',
        'Tumauini',
        'Balbalan',
        'Lubuagan',
        'Pasil',
        'Pinukpuk',
        'Rizal',
        'Tabuk',
        'Tanudan',
        'Tinglayan',
        'Agoo',
        'Aringay',
        'Bacnotan',
        'Bagulin',
        'Balaoan',
        'Bangar',
        'Bauang',
        'Burgos',
        'Caba',
        'Luna',
        'Naguilian',
        'Pugo',
        'Rosario',
        'San Fernando',
        'San Gabriel',
        'San Juan',
        'Santo Tomas',
        'Santol',
        'Sudipen',
        'Tubao',
        'Alaminos',
        'Bay',
        'Biñan',
        'Cabuyao',
        'Calamba',
        'Calauan',
        'Cavinti',
        'Famy',
        'Kalayaan',
        'Liliw',
        'Los Baños',
        'Luisiana',
        'Lumban',
        'Mabitac',
        'Magdalena',
        'Majayjay',
        'Nagcarlan',
        'Paete',
        'Pagsanjan',
        'Pakil',
        'Pangil',
        'Pila',
        'Rizal',
        'San Pablo',
        'San Pedro',
        'Santa Cruz',
        'Santa Maria',
        'Santa Rosa',
        'Siniloan',
        'Victoria',
        'Bacolod',
        'Balo-i',
        'Baroy',
        'Iligan',
        'Kapatagan',
        'Kauswagan',
        'Kolambugan',
        'Lala',
        'Linamon',
        'Magsaysay',
        'Maigo',
        'Matungao',
        'Munai',
        'Nunungan',
        'Pantao Ragat',
        'Pantar',
        'Poona Piagapo',
        'Salvador',
        'Sapad',
        'Sultan Naga Dimaporo',
        'Tagoloan',
        'Tangcal',
        'Tubod',
        'Amai Manabilang',
        'Bacolod-Kalawi',
        'Balabagan',
        'Balindong',
        'Bayang',
        'Binidayan',
        'Buadiposo-Buntong',
        'Bubong',
        'Butig',
        'Calanogas',
        'Ditsaan-Ramain',
        'Ganassi',
        'Kapai',
        'Kapatagan',
        'Lumba-Bayabao',
        'Lumbaca-Unayan',
        'Lumbatan',
        'Lumbayanague',
        'Madalum',
        'Madamba',
        'Maguing',
        'Malabang',
        'Marantao',
        'Marawi',
        'Marogong',
        'Masiu',
        'Mulondo',
        'Pagayawan',
        'Piagapo',
        'Picong',
        'Poona Bayabao',
        'Pualas',
        'Saguiaran',
        'Sultan Dumalondong',
        'Tagoloan II',
        'Tamparan',
        'Taraka',
        'Tubaran',
        'Tugaya',
        'Wao',
        'Abuyog',
        'Alangalang',
        'Albuera',
        'Babatngon',
        'Barugo',
        'Bato',
        'Baybay',
        'Burauen',
        'Calubian',
        'Capoocan',
        'Carigara',
        'Dagami',
        'Dulag',
        'Hilongos',
        'Hindang',
        'Inopacan',
        'Isabel',
        'Jaro',
        'Javier',
        'Julita',
        'Kananga',
        'La Paz',
        'Leyte',
        'MacArthur',
        'Mahaplag',
        'Matag-ob',
        'Matalom',
        'Mayorga',
        'Merida',
        'Ormoc',
        'Palo',
        'Palompon',
        'Pastrana',
        'San Isidro',
        'San Miguel',
        'Santa Fe',
        'Tabango',
        'Tabontabon',
        'Tacloban',
        'Tanauan',
        'Tolosa',
        'Tunga',
        'Villaba',
        'Barira',
        'Buldon',
        'Cotabato',
        'Datu Blah T. Sinsuat',
        'Datu Odin Sinsuat',
        'Kabuntalan',
        'Matanog',
        'Northern Kabuntalan',
        'Parang',
        'Sultan Kudarat',
        'Sultan Mastura',
        'Talitay',
        'Upi',
        'Ampatuan',
        'Buluan',
        'Datu Abdullah Sangki',
        'Datu Anggal Midtimbang',
        'Datu Hoffer Ampatuan',
        'Datu Montawal',
        'Datu Paglas',
        'Datu Piang',
        'Datu Salibo',
        'Datu Saudi-Ampatuan',
        'Datu Unsay',
        'General Salipada K. Pendatun',
        'Guindulungan',
        'Mamasapano',
        'Mangudadatu',
        'Pagalungan',
        'Paglat',
        'Pandag',
        'Rajah Buayan',
        'Shariff Aguak',
        'Shariff Saydona Mustapha',
        'South Upi',
        'Sultan sa Barongis',
        'Talayan',
        'Boac',
        'Buenavista',
        'Gasan',
        'Mogpog',
        'Santa Cruz',
        'Torrijos',
        'Aroroy',
        'Baleno',
        'Balud',
        'Batuan',
        'Cataingan',
        'Cawayan',
        'Claveria',
        'Dimasalang',
        'Esperanza',
        'Mandaon',
        'Masbate',
        'Milagros',
        'Mobo',
        'Monreal',
        'Palanas',
        'Pio V. Corpus',
        'Placer',
        'San Fernando',
        'San Jacinto',
        'San Pascual',
        'Uson',
        'Caloocan',
        'Las Piñas',
        'Makati',
        'Malabon',
        'Mandaluyong',
        'Manila',
        'Marikina',
        'Muntinlupa',
        'Navotas',
        'Parañaque',
        'Pasay',
        'Pasig',
        'Pateros',
        'Quezon',
        'San Juan',
        'Taguig',
        'Valenzuela',
        'Aloran',
        'Baliangao',
        'Bonifacio',
        'Calamba',
        'Clarin',
        'Concepcion',
        'Don Victoriano Chiongbian',
        'Jimenez',
        'Lopez Jaena',
        'Oroquieta',
        'Ozamiz',
        'Panaon',
        'Plaridel',
        'Sapang Dalaga',
        'Sinacaban',
        'Tangub',
        'Tudela',
        'Alubijid',
        'Balingasag',
        'Balingoan',
        'Binuangan',
        'Cagayan de Oro',
        'Claveria',
        'El Salvador',
        'Gingoog',
        'Gitagum',
        'Initao',
        'Jasaan',
        'Kinoguitan',
        'Lagonglong',
        'Laguindingan',
        'Libertad',
        'Lugait',
        'Magsaysay',
        'Manticao',
        'Medina',
        'Naawan',
        'Opol',
        'Salay',
        'Sugbongcogon',
        'Tagoloan',
        'Talisayan',
        'Villanueva',
        'Barlig',
        'Bauko',
        'Besao',
        'Bontoc',
        'Natonin',
        'Paracelis',
        'Sabangan',
        'Sadanga',
        'Sagada',
        'Tadian',
        'Bacolod',
        'Bago',
        'Binalbagan',
        'Cadiz',
        'Calatrava',
        'Candoni',
        'Cauayan',
        'Don Salvador Benedicto',
        'Enrique B. Magalona',
        'Escalante',
        'Himamaylan',
        'Hinigaran',
        'Hinoba-an',
        'Ilog',
        'Isabela',
        'Kabankalan',
        'La Carlota',
        'La Castellana',
        'Manapla',
        'Moises Padilla',
        'Murcia',
        'Pontevedra',
        'Pulupandan',
        'Sagay',
        'San Carlos',
        'San Enrique',
        'Silay',
        'Sipalay',
        'Talisay',
        'Toboso',
        'Valladolid',
        'Victorias',
        'Amlan',
        'Ayungon',
        'Bacong',
        'Bais',
        'Basay',
        'Bayawan',
        'Bindoy',
        'Canlaon',
        'Dauin',
        'Dumaguete',
        'Guihulngan',
        'Jimalalud',
        'La Libertad',
        'Mabinay',
        'Manjuyod',
        'Pamplona',
        'San Jose',
        'Santa Catalina',
        'Siaton',
        'Sibulan',
        'Tanjay',
        'Tayasan',
        'Valencia',
        'Vallehermoso',
        'Zamboanguita',
        'Allen',
        'Biri',
        'Bobon',
        'Capul',
        'Catarman',
        'Catubig',
        'Gamay',
        'Laoang',
        'Lapinig',
        'Las Navas',
        'Lavezares',
        'Lope de Vega',
        'Mapanas',
        'Mondragon',
        'Palapag',
        'Pambujan',
        'Rosario',
        'San Antonio',
        'San Isidro',
        'San Jose',
        'San Roque',
        'San Vicente',
        'Silvino Lobos',
        'Victoria',
        'Aliaga',
        'Bongabon',
        'Cabanatuan',
        'Cabiao',
        'Carranglan',
        'Cuyapo',
        'Gabaldon',
        'Gapan',
        'General Mamerto Natividad',
        'General Tinio',
        'Guimba',
        'Jaen',
        'Laur',
        'Licab',
        'Llanera',
        'Lupao',
        'Muñoz',
        'Nampicuan',
        'Palayan',
        'Pantabangan',
        'Peñaranda',
        'Quezon',
        'Rizal',
        'San Antonio',
        'San Isidro',
        'San Jose',
        'San Leonardo',
        'Santa Rosa',
        'Santo Domingo',
        'Talavera',
        'Talugtug',
        'Zaragoza',
        'Alfonso Castañeda',
        'Ambaguio',
        'Aritao',
        'Bagabag',
        'Bambang',
        'Bayombong',
        'Diadi',
        'Dupax del Norte',
        'Dupax del Sur',
        'Kasibu',
        'Kayapa',
        'Quezon',
        'Santa Fe',
        'Solano',
        'Villaverde',
        'Abra de Ilog',
        'Calintaan',
        'Looc',
        'Lubang',
        'Magsaysay',
        'Mamburao',
        'Paluan',
        'Rizal',
        'Sablayan',
        'San Jose',
        'Santa Cruz',
        'Baco',
        'Bansud',
        'Bongabong',
        'Bulalacao',
        'Calapan',
        'Gloria',
        'Mansalay',
        'Naujan',
        'Pinamalayan',
        'Pola',
        'Puerto Galera',
        'Roxas',
        'San Teodoro',
        'Socorro',
        'Victoria',
        'Aborlan',
        'Agutaya',
        'Araceli',
        'Balabac',
        'Bataraza',
        'Brooke\'s Point',
        'Busuanga',
        'Cagayancillo',
        'Coron',
        'Culion',
        'Cuyo',
        'Dumaran',
        'El Nido',
        'Kalayaan',
        'Linapacan',
        'Magsaysay',
        'Narra',
        'Puerto Princesa',
        'Quezon',
        'Rizal',
        'Roxas',
        'San Vicente',
        'Sofronio Española',
        'Taytay',
        'Angeles',
        'Apalit',
        'Arayat',
        'Bacolor',
        'Candaba',
        'Floridablanca',
        'Guagua',
        'Lubao',
        'Mabalacat',
        'Macabebe',
        'Magalang',
        'Masantol',
        'Mexico',
        'Minalin',
        'Porac',
        'San Fernando',
        'San Luis',
        'San Simon',
        'Santa Ana',
        'Santa Rita',
        'Santo Tomas',
        'Sasmuan',
        'Agno',
        'Aguilar',
        'Alaminos',
        'Alcala',
        'Anda',
        'Asingan',
        'Balungao',
        'Bani',
        'Basista',
        'Bautista',
        'Bayambang',
        'Binalonan',
        'Binmaley',
        'Bolinao',
        'Bugallon',
        'Burgos',
        'Calasiao',
        'Dagupan',
        'Dasol',
        'Infanta',
        'Labrador',
        'Laoac',
        'Lingayen',
        'Mabini',
        'Malasiqui',
        'Manaoag',
        'Mangaldan',
        'Mangatarem',
        'Mapandan',
        'Natividad',
        'Pozorrubio',
        'Rosales',
        'San Carlos',
        'San Fabian',
        'San Jacinto',
        'San Manuel',
        'San Nicolas',
        'San Quintin',
        'Santa Barbara',
        'Santa Maria',
        'Santo Tomas',
        'Sison',
        'Sual',
        'Tayug',
        'Umingan',
        'Urbiztondo',
        'Urdaneta',
        'Villasis',
        'Agdangan',
        'Alabat',
        'Atimonan',
        'Buenavista',
        'Burdeos',
        'Calauag',
        'Candelaria',
        'Catanauan',
        'Dolores',
        'General Luna',
        'General Nakar',
        'Guinayangan',
        'Gumaca',
        'Infanta',
        'Jomalig',
        'Lopez',
        'Lucban',
        'Lucena',
        'Macalelon',
        'Mauban',
        'Mulanay',
        'Padre Burgos',
        'Pagbilao',
        'Panukulan',
        'Patnanungan',
        'Perez',
        'Pitogo',
        'Plaridel',
        'Polillo',
        'Quezon',
        'Real',
        'Sampaloc',
        'San Andres',
        'San Antonio',
        'San Francisco',
        'San Narciso',
        'Sariaya',
        'Tagkawayan',
        'Tayabas',
        'Tiaong',
        'Unisan',
        'Aglipay',
        'Cabarroguis',
        'Diffun',
        'Maddela',
        'Nagtipunan',
        'Saguday',
        'Angono',
        'Antipolo',
        'Baras',
        'Binangonan',
        'Cainta',
        'Cardona',
        'Jalajala',
        'Morong',
        'Pililla',
        'Rodriguez',
        'San Mateo',
        'Tanay',
        'Taytay',
        'Teresa',
        'Alcantara',
        'Banton',
        'Cajidiocan',
        'Calatrava',
        'Concepcion',
        'Corcuera',
        'Ferrol',
        'Looc',
        'Magdiwang',
        'Odiongan',
        'Romblon',
        'San Agustin',
        'San Andres',
        'San Fernando',
        'San Jose',
        'Santa Fe',
        'Santa Maria',
        'Almagro',
        'Basey',
        'Calbayog',
        'Calbiga',
        'Catbalogan',
        'Daram',
        'Gandara',
        'Hinabangan',
        'Jiabong',
        'Marabut',
        'Matuguinao',
        'Motiong',
        'Pagsanghan',
        'Paranas',
        'Pinabacdao',
        'San Jorge',
        'San Jose de Buan',
        'San Sebastian',
        'Santa Margarita',
        'Santa Rita',
        'Santo Niño',
        'Tagapul-an',
        'Talalora',
        'Tarangnan',
        'Villareal',
        'Zumarraga',
        'Alabel',
        'Glan',
        'Kiamba',
        'Maasim',
        'Maitum',
        'Malapatan',
        'Malungon',
        'Enrique Villanueva',
        'Larena',
        'Lazi',
        'Maria',
        'San Juan',
        'Siquijor',
        'Barcelona',
        'Bulan',
        'Bulusan',
        'Casiguran',
        'Castilla',
        'Donsol',
        'Gubat',
        'Irosin',
        'Juban',
        'Magallanes',
        'Matnog',
        'Pilar',
        'Prieto Diaz',
        'Santa Magdalena',
        'Sorsogon',
        'Banga',
        'General Santos',
        'Koronadal',
        'Lake Sebu',
        'Norala',
        'Polomolok',
        'Santo Niño',
        'Surallah',
        'T\'Boli',
        'Tampakan',
        'Tantangan',
        'Tupi',
        'Anahawan',
        'Bontoc',
        'Hinunangan',
        'Hinundayan',
        'Libagon',
        'Liloan',
        'Limasawa',
        'Maasin',
        'Macrohon',
        'Malitbog',
        'Padre Burgos',
        'Pintuyan',
        'Saint Bernard',
        'San Francisco',
        'San Juan',
        'San Ricardo',
        'Silago',
        'Sogod',
        'Tomas Oppus',
        'Bagumbayan',
        'Columbio',
        'Esperanza',
        'Isulan',
        'Kalamansig',
        'Lambayong',
        'Lebak',
        'Lutayan',
        'Palimbang',
        'President Quirino',
        'Senator Ninoy Aquino',
        'Tacurong',
        'Banguingui',
        'Hadji Panglima Tahil',
        'Indanan',
        'Jolo',
        'Kalingalan Caluang',
        'Lugus',
        'Luuk',
        'Maimbung',
        'Omar',
        'Panamao',
        'Pandami',
        'Panglima Estino',
        'Pangutaran',
        'Parang',
        'Pata',
        'Patikul',
        'Siasi',
        'Talipao',
        'Tapul',
        'Alegria',
        'Bacuag',
        'Burgos',
        'Claver',
        'Dapa',
        'Del Carmen',
        'General Luna',
        'Gigaquit',
        'Mainit',
        'Malimono',
        'Pilar',
        'Placer',
        'San Benito',
        'San Francisco',
        'San Isidro',
        'Santa Monica',
        'Sison',
        'Socorro',
        'Surigao',
        'Tagana-an',
        'Tubod',
        'Barobo',
        'Bayabas',
        'Bislig',
        'Cagwait',
        'Cantilan',
        'Carmen',
        'Carrascal',
        'Cortes',
        'Hinatuan',
        'Lanuza',
        'Lianga',
        'Lingig',
        'Madrid',
        'Marihatag',
        'San Agustin',
        'San Miguel',
        'Tagbina',
        'Tago',
        'Tandag',
        'Anao',
        'Bamban',
        'Camiling',
        'Capas',
        'Concepcion',
        'Gerona',
        'La Paz',
        'Mayantoc',
        'Moncada',
        'Paniqui',
        'Pura',
        'Ramos',
        'San Clemente',
        'San Jose',
        'San Manuel',
        'Santa Ignacia',
        'Tarlac',
        'Victoria',
        'Bongao',
        'Languyan',
        'Mapun',
        'Panglima Sugala',
        'Sapa-Sapa',
        'Sibutu',
        'Simunul',
        'Sitangkai',
        'South Ubian',
        'Tandubas',
        'Turtle Islands',
        'Botolan',
        'Cabangan',
        'Candelaria',
        'Castillejos',
        'Iba',
        'Masinloc',
        'Olongapo',
        'Palauig',
        'San Antonio',
        'San Felipe',
        'San Marcelino',
        'San Narciso',
        'Santa Cruz',
        'Subic',
        'Baliguian',
        'Dapitan',
        'Dipolog',
        'Godod',
        'Gutalac',
        'Jose Dalman',
        'Kalawit',
        'Katipunan',
        'La Libertad',
        'Labason',
        'Leon B. Postigo',
        'Liloy',
        'Manukan',
        'Mutia',
        'Piñan',
        'Polanco',
        'Rizal',
        'Roxas',
        'Salug',
        'Sergio Osmeña',
        'Siayan',
        'Sibuco',
        'Sibutad',
        'Sindangan',
        'Siocon',
        'Sirawai',
        'Tampilisan',
        'Aurora',
        'Bayog',
        'Dimataling',
        'Dinas',
        'Dumalinao',
        'Dumingag',
        'Guipos',
        'Josefina',
        'Kumalarang',
        'Labangan',
        'Lakewood',
        'Lapuyan',
        'Mahayag',
        'Margosatubig',
        'Midsalip',
        'Molave',
        'Pagadian',
        'Pitogo',
        'Ramon Magsaysay',
        'San Miguel',
        'San Pablo',
        'Sominot',
        'Tabina',
        'Tambulig',
        'Tigbao',
        'Tukuran',
        'Vincenzo A. Sagun',
        'Zamboanga',
        'Alicia',
        'Buug',
        'Diplahan',
        'Imelda',
        'Ipil',
        'Kabasalan',
        'Mabuhay',
        'Malangas',
        'Naga',
        'Olutanga',
        'Payao',
        'Roseller Lim',
        'Siay',
        'Talusan',
        'Titay',
        'Tungawan'
    ]

    cities_in_ph = [city.upper() for city in cities_in_ph]
    return city.upper() in cities_in_ph

province_dict = {
    'Manila': 'Metro Manila',
    'Compostela Valley': 'Davao de Oro'
}

def is_valid_province(province):
    provinces_in_ph = [
        'Abra',
        'Agusan del Norte',
        'Agusan del Sur',
        'Aklan',
        'Albay',
        'Antique',
        'Apayao',
        'Aurora',
        'Basilan',
        'Bataan',
        'Batanes',
        'Batangas',
        'Benguet',
        'Biliran',
        'Bohol',
        'Bukidnon',
        'Bulacan',
        'Cagayan',
        'Camarines Norte',
        'Camarines Sur',
        'Camiguin',
        'Capiz',
        'Catanduanes',
        'Cavite',
        'Cebu',
        'Cotabato',
        'Davao de Oro',
        'Davao del Norte',
        'Davao del Sur',
        'Davao Occidental',
        'Davao Oriental',
        'Dinagat Islands',
        'Eastern Samar',
        'Guimaras',
        'Ifugao',
        'Ilocos Norte',
        'Ilocos Sur',
        'Iloilo',
        'Isabela',
        'Kalinga',
        'La Union',
        'Laguna',
        'Lanao del Norte',
        'Lanao del Sur',
        'Leyte',
        'Maguindanao',
        'Marinduque',
        'Masbate',
        'Misamis Occidental',
        'Misamis Oriental',
        'Mountain Province',
        'Negros Occidental',
        'Negros Oriental',
        'Northern Samar',
        'Nueva Ecija',
        'Nueva Vizcaya',
        'Occidental Mindoro',
        'Oriental Mindoro',
        'Palawan',
        'Pampanga',
        'Pangasinan',
        'Quezon',
        'Quirino',
        'Rizal',
        'Romblon',
        'Samar',
        'Sarangani',
        'Siquijor',
        'Sorsogon',
        'South Cotabato',
        'Southern Leyte',
        'Sultan Kudarat',
        'Sulu',
        'Surigao del Norte',
        'Surigao del Sur',
        'Tarlac',
        'Tawi-Tawi',
        'Zambales',
        'Zamboanga del Norte',
        'Zamboanga del Sur',
        'Zamboanga Sibugay',
        'Metro Manila',
        'Butuan',
        'Baguio',
        'Naga',
        'Cebu',
        'Lapu-Lapu',
        'Mandaue',
        'Davao',
        'Iloilo',
        'Santiago',
        'Iligan',
        'Ormoc',
        'Tacloban',
        'Cotabato',
        'Cagayan de Oro',
        'Bacolod',
        'Puerto Princesa',
        'Angeles',
        'Dagupan',
        'Lucena',
        'General Santos',
        'Olongapo',
        'Zamboanga',
    ]

    provinces_in_ph = [province.upper() for province in provinces_in_ph]
    return province.upper() in provinces_in_ph